import "./globals.css";
import "react-responsive-modal/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReduxProvider } from "../redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} m-5 md:mx-40 xl:mx-96`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
